import { CatmullRomCurve3, Vector3 } from "three";
import type { Anatomy, CenterlinePoint, VesselBranch } from "./types";

/**
 * Procedural "normal" arterial anatomy used for development of the engine.
 *
 * IMPORTANT: this is a parametric, anatomically-plausible stand-in — NOT a real
 * segmented dataset. It exists so the rendering + physics + UX can be built and
 * tuned against real centerlines today. The production path replaces this module's
 * output with assets generated by the license-clean pipeline
 * (contrast CTA -> TotalSegmentator -> VMTK centerlines -> glTF + JSON sidecar).
 * The downstream code only depends on the `Anatomy` interface, so that swap is local.
 *
 * Body frame, units in cm: +y cranial, +x patient-left, +z anterior.
 */

interface Ctrl {
  p: [number, number, number];
  r: number;
}

/** Loft a smooth, densely-sampled centerline through control points, carrying radius + arc length. */
function buildBranch(
  id: string,
  name: string,
  attenuation: number,
  ctrls: Ctrl[],
  samples = 64
): VesselBranch {
  const curve = new CatmullRomCurve3(
    ctrls.map((c) => new Vector3(...c.p)),
    false,
    "centripetal"
  );
  const points: CenterlinePoint[] = [];
  let s = 0;
  let prev: Vector3 | null = null;
  for (let i = 0; i <= samples; i++) {
    const t = i / samples;
    const pos = curve.getPoint(t);
    // Map normalized t onto the control radii (piecewise-linear).
    const f = t * (ctrls.length - 1);
    const lo = Math.min(ctrls.length - 1, Math.floor(f));
    const hi = Math.min(ctrls.length - 1, lo + 1);
    const radius = ctrls[lo].r + (ctrls[hi].r - ctrls[lo].r) * (f - lo);
    if (prev) s += pos.distanceTo(prev);
    points.push({ pos, radius, s });
    prev = pos;
  }
  return { id, name, attenuation, points };
}

export function buildNormalAnatomy(): Anatomy {
  // --- Aorta: femoral-access bifurcation (y=0) up through abdominal + thoracic to the arch. ---
  const aorta = buildBranch("aorta", "Aorta", 1.0, [
    { p: [0.0, 0.0, 0.0], r: 0.9 }, // aortic bifurcation (~L4)
    { p: [0.1, 4.0, 0.4], r: 1.0 },
    { p: [0.0, 9.0, 0.8], r: 1.05 }, // infrarenal
    { p: [-0.2, 13.5, 0.6], r: 1.1 }, // renal level
    { p: [0.0, 19.0, 0.2], r: 1.15 }, // diaphragm
    { p: [0.3, 26.0, -0.4], r: 1.2 }, // descending thoracic
    { p: [0.6, 31.5, -1.2], r: 1.25 }, // distal arch
    { p: [-0.4, 34.2, -0.2], r: 1.25 }, // arch apex
    { p: [-1.4, 32.5, 1.6], r: 1.3 } // ascending aorta / root
  ]);

  // --- Iliac arteries down to the femoral access points. ---
  const rightIliac = buildBranch("iliac_r", "Right common iliac", 0.85, [
    { p: [0.0, 0.0, 0.0], r: 0.55 },
    { p: [-2.2, -3.2, 0.2], r: 0.52 },
    { p: [-3.4, -7.0, 0.0], r: 0.5 },
    { p: [-3.8, -11.5, -0.2], r: 0.48 } // R common femoral (access)
  ]);
  const leftIliac = buildBranch("iliac_l", "Left common iliac", 0.85, [
    { p: [0.0, 0.0, 0.0], r: 0.55 },
    { p: [2.2, -3.2, 0.2], r: 0.52 },
    { p: [3.4, -7.0, 0.0], r: 0.5 },
    { p: [3.8, -11.5, -0.2], r: 0.48 }
  ]);

  // --- Renal arteries (off the aorta at the renal level). ---
  const leftRenal = buildBranch("renal_l", "Left renal artery", 0.7, [
    { p: [-0.2, 13.5, 0.6], r: 0.3 },
    { p: [2.0, 13.8, 0.2], r: 0.28 },
    { p: [4.2, 13.4, -0.4], r: 0.26 }
  ]);
  const rightRenal = buildBranch("renal_r", "Right renal artery", 0.7, [
    { p: [-0.2, 13.5, 0.6], r: 0.3 },
    { p: [-2.2, 13.2, 0.2], r: 0.28 },
    { p: [-4.4, 12.9, -0.4], r: 0.26 }
  ]);

  // --- Arch great vessels. ---
  const innominate = buildBranch("innominate", "Brachiocephalic trunk", 0.75, [
    { p: [0.6, 31.5, -1.2], r: 0.45 },
    { p: [-1.0, 34.5, -1.0], r: 0.4 },
    { p: [-2.2, 37.0, -0.8], r: 0.36 }
  ]);
  const leftCarotid = buildBranch("carotid_l", "Left common carotid", 0.7, [
    { p: [0.1, 33.2, -0.9], r: 0.34 },
    { p: [0.6, 37.0, -0.6], r: 0.31 },
    { p: [1.0, 40.5, -0.4], r: 0.29 }
  ]);
  const leftSubclavian = buildBranch("subclavian_l", "Left subclavian", 0.72, [
    { p: [-0.3, 33.6, -1.1], r: 0.38 },
    { p: [2.6, 35.6, -1.6], r: 0.34 },
    { p: [5.4, 36.2, -2.0], r: 0.31 }
  ]);

  const branches = [
    aorta,
    rightIliac,
    leftIliac,
    leftRenal,
    rightRenal,
    innominate,
    leftCarotid,
    leftSubclavian
  ];

  const ostium = (b: VesselBranch) => b.points[0].pos.clone();

  return {
    id: "normal-v0",
    name: "Normal arterial anatomy (procedural v0)",
    branches,
    access: [
      {
        id: "rcfa",
        name: "Right common femoral artery",
        pos: rightIliac.points[rightIliac.points.length - 1].pos.clone(),
        dir: new Vector3(0.32, 1, 0.04).normalize(),
        branchId: "iliac_r"
      },
      {
        // Mirror of the right access across the sagittal plane: the left femoral sits at +x and
        // the iliac runs up toward the bifurcation at x=0, so the insertion direction tilts to −x.
        id: "lcfa",
        name: "Left common femoral artery",
        pos: leftIliac.points[leftIliac.points.length - 1].pos.clone(),
        dir: new Vector3(-0.32, 1, 0.04).normalize(),
        branchId: "iliac_l"
      }
    ],
    targets: [
      { id: "t_renal_l", name: "Left renal ostium", pos: ostium(leftRenal), acceptance: 0.6, viaBranchId: "renal_l" },
      { id: "t_renal_r", name: "Right renal ostium", pos: ostium(rightRenal), acceptance: 0.6, viaBranchId: "renal_r" },
      { id: "t_carotid_l", name: "Left common carotid ostium", pos: ostium(leftCarotid), acceptance: 0.6, viaBranchId: "carotid_l" },
      { id: "t_innominate", name: "Brachiocephalic ostium", pos: ostium(innominate), acceptance: 0.7, viaBranchId: "innominate" }
    ],
    provenance: {
      source: "Procedural (IRsim parametric generator)",
      license: "CC0 / generated",
      note: "Anatomically-plausible placeholder. Replace with VMTK-derived centerlines from a license-clean CTA before any clinical-credibility claim."
    }
  };
}
